[package]
name = "solyan-airplay-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
airplay2-core = { package = "airplay-core", git = "https://github.com/lmcgartland/airplay2-rs", rev = "a2f980cf25bf13ae20158497cc2d2ea69cd88fa7" }
airplay2-discovery = { package = "airplay-discovery", git = "https://github.com/lmcgartland/airplay2-rs", rev = "a2f980cf25bf13ae20158497cc2d2ea69cd88fa7" }
