[workspace]
members = [
  "crates/solyan-airplay-cli",
  "crates/solyan-airplay-gui",
  "crates/airplay-core",
  "crates/audio-capture",
]
exclude = ["vendor/airplay-audio", "vendor/airplay-resampler"]
resolver = "2"

[workspace.package]
version = "0.2.2"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["SolYan"]

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync", "net", "io-util"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
thiserror = "1"
crossbeam-channel = "0.5"

[patch."https://github.com/lmcgartland/airplay2-rs"]
airplay-audio = { path = "vendor/airplay-audio" }
airplay-resampler = { path = "vendor/airplay-resampler" }
